-- NeuroSpark: esquema consolidado, reparación de datos y RLS.
-- Compatible con una base nueva y con ejecuciones parciales anteriores.
-- No elimina filas. Los duplicados quedan visibles en vistas de auditoría.

begin;

create or replace function public._ns_safe_jsonb(value text)
returns jsonb
language plpgsql
immutable
set search_path = public, pg_temp
as $$
begin
    if value is null or btrim(value) = '' then
        return '{}'::jsonb;
    end if;
    return value::jsonb;
exception
    when others then
        return jsonb_build_object('legacy_value', value);
end
$$;

-- ---------------------------------------------------------------------------
-- 1. Tablas base. CREATE TABLE cubre instalaciones nuevas; ALTER cubre
--    instalaciones existentes o migraciones ejecutadas parcialmente.
-- ---------------------------------------------------------------------------

create table if not exists public.user_profiles (
    id bigint generated by default as identity primary key,
    email text,
    state_data jsonb not null default '{}'::jsonb,
    user_id uuid,
    parent_user_id uuid,
    user_email text,
    parent_email text,
    alias text,
    full_name text,
    age smallint,
    mode text,
    is_primary boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.user_profiles
    add column if not exists id bigint generated by default as identity,
    add column if not exists email text,
    add column if not exists state_data jsonb default '{}'::jsonb,
    add column if not exists user_id uuid,
    add column if not exists parent_user_id uuid,
    add column if not exists user_email text,
    add column if not exists parent_email text,
    add column if not exists alias text,
    add column if not exists full_name text,
    add column if not exists age smallint,
    add column if not exists mode text,
    add column if not exists is_primary boolean not null default true,
    add column if not exists created_at timestamptz not null default now(),
    add column if not exists updated_at timestamptz not null default now();

do $$
declare
    state_type text;
begin
    select columns.udt_name
    into state_type
    from information_schema.columns
    where columns.table_schema = 'public'
      and columns.table_name = 'user_profiles'
      and columns.column_name = 'state_data';

    if state_type is distinct from 'jsonb' then
        execute '
            alter table public.user_profiles
            alter column state_data type jsonb
            using public._ns_safe_jsonb(state_data::text)
        ';
    end if;
end
$$;

update public.user_profiles
set state_data = '{}'::jsonb
where state_data is null;

alter table public.user_profiles
    alter column state_data set default '{}'::jsonb,
    alter column state_data set not null;

create table if not exists public.correos (
    id bigint generated by default as identity primary key,
    user_email text,
    parent_email text,
    child_user_id uuid,
    parent_user_id uuid,
    alias text,
    full_name text,
    age smallint,
    mode text,
    is_primary boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.correos
    add column if not exists id bigint generated by default as identity,
    add column if not exists user_email text,
    add column if not exists parent_email text,
    add column if not exists child_user_id uuid,
    add column if not exists parent_user_id uuid,
    add column if not exists alias text,
    add column if not exists full_name text,
    add column if not exists age smallint,
    add column if not exists mode text,
    add column if not exists is_primary boolean not null default true,
    add column if not exists created_at timestamptz not null default now(),
    add column if not exists updated_at timestamptz not null default now();

-- ---------------------------------------------------------------------------
-- 2. Recuperación no destructiva de una tabla equivalente renombrada.
--    Solo se consideran nombres históricos conocidos y columnas compatibles.
-- ---------------------------------------------------------------------------

do $$
declare
    candidate text;
    has_email boolean;
    has_state boolean;
    migrated_count bigint;
begin
    foreach candidate in array array['profiles', 'user_profile', 'usuarios_perfiles']
    loop
        if to_regclass(format('public.%I', candidate)) is null then
            continue;
        end if;

        select exists (
            select 1 from information_schema.columns
            where table_schema = 'public'
              and table_name = candidate
              and column_name = 'email'
        ) into has_email;

        select exists (
            select 1 from information_schema.columns
            where table_schema = 'public'
              and table_name = candidate
              and column_name = 'state_data'
        ) into has_state;

        if has_email and has_state then
            execute format(
                'insert into public.user_profiles (email, user_email, state_data)
                 select source.email::text,
                        source.email::text,
                        public._ns_safe_jsonb(source.state_data::text)
                 from public.%I as source
                 where source.email is not null
                   and not exists (
                       select 1 from public.user_profiles as target
                       where lower(coalesce(target.user_email, target.email)) =
                             lower(source.email::text)
                   )',
                candidate
            );
            get diagnostics migrated_count = row_count;
            raise notice 'Tabla equivalente public.% detectada: % filas copiadas sin eliminar el origen.',
                candidate, migrated_count;
        else
            raise notice 'Tabla public.% detectada, pero no contiene email y state_data; no fue modificada.',
                candidate;
        end if;
    end loop;
end
$$;

-- ---------------------------------------------------------------------------
-- 3. Backfill de identidades desde auth.users.
-- ---------------------------------------------------------------------------

update public.user_profiles
set user_email = coalesce(nullif(btrim(user_email), ''), nullif(btrim(email), ''))
where user_email is null or btrim(user_email) = '';

update public.user_profiles
set email = coalesce(nullif(btrim(email), ''), nullif(btrim(user_email), ''))
where email is null or btrim(email) = '';

update public.user_profiles as profile
set user_id = auth_user.id
from auth.users as auth_user
where profile.user_id is null
  and auth_user.email is not null
  and lower(auth_user.email) = lower(coalesce(profile.user_email, profile.email));

update public.correos as link
set child_user_id = auth_user.id
from auth.users as auth_user
where link.child_user_id is null
  and auth_user.email is not null
  and lower(auth_user.email) = lower(link.user_email);

update public.correos as link
set parent_user_id = auth_user.id
from auth.users as auth_user
where link.parent_user_id is null
  and auth_user.email is not null
  and lower(auth_user.email) = lower(link.parent_email);

-- Se elige primero un vínculo principal determinista. Así el backfill siguiente
-- nunca toma al azar una de varias filas antiguas para el mismo hijo.
with ranked as (
    select link.id,
           row_number() over (
               partition by link.child_user_id
               order by link.is_primary desc, link.updated_at desc, link.id
           ) as position
    from public.correos as link
    where link.child_user_id is not null
)
update public.correos as link
set is_primary = ranked.position = 1
from ranked
where link.id = ranked.id
  and link.is_primary is distinct from (ranked.position = 1);

update public.user_profiles as profile
set parent_email = link.parent_email,
    parent_user_id = coalesce(profile.parent_user_id, link.parent_user_id),
    alias = coalesce(profile.alias, link.alias),
    full_name = coalesce(profile.full_name, link.full_name),
    age = coalesce(profile.age, link.age),
    mode = coalesce(profile.mode, link.mode)
from public.correos as link
where profile.user_id = link.child_user_id
  and link.is_primary;

-- ---------------------------------------------------------------------------
-- 4. Auditoría y resolución no destructiva de duplicados.
--    Se mantiene una fila principal determinista; ninguna fila se elimina.
-- ---------------------------------------------------------------------------

with ranked as (
    select profile.id,
           row_number() over (
               partition by profile.user_id
               order by profile.is_primary desc, profile.updated_at desc, profile.id
           ) as position
    from public.user_profiles as profile
    where profile.user_id is not null
)
update public.user_profiles as profile
set is_primary = ranked.position = 1
from ranked
where profile.id = ranked.id
  and profile.is_primary is distinct from (ranked.position = 1);

create or replace view public.neurospark_correos_duplicates as
select
    link.child_user_id,
    count(*)::integer as duplicate_count,
    jsonb_agg(to_jsonb(link) order by link.is_primary desc, link.updated_at desc, link.id) as records
from public.correos as link
where link.child_user_id is not null
group by link.child_user_id
having count(*) > 1;

create or replace view public.neurospark_profile_duplicates as
select
    'user_id'::text as duplicate_type,
    profile.user_id::text as duplicate_key,
    count(*)::integer as duplicate_count,
    jsonb_agg(to_jsonb(profile) order by profile.is_primary desc, profile.updated_at desc, profile.id) as records
from public.user_profiles as profile
where profile.user_id is not null
group by profile.user_id
having count(*) > 1
union all
select
    'alias'::text,
    lower(profile.alias),
    count(*)::integer,
    jsonb_agg(to_jsonb(profile) order by profile.updated_at desc, profile.id)
from public.user_profiles as profile
where profile.alias is not null
  and btrim(profile.alias) <> ''
group by lower(profile.alias)
having count(*) > 1
union all
select
    'user_email'::text,
    lower(profile.user_email),
    count(*)::integer,
    jsonb_agg(to_jsonb(profile) order by profile.updated_at desc, profile.id)
from public.user_profiles as profile
where profile.user_email is not null
  and btrim(profile.user_email) <> ''
group by lower(profile.user_email)
having count(*) > 1;

create or replace view public.neurospark_schema_inventory as
select
    tables.table_name,
    tables.table_type
from information_schema.tables
where tables.table_schema = 'public'
union all
select
    views.table_name,
    'VIEW'::text
from information_schema.views as views
where views.table_schema = 'public';

revoke all on public.neurospark_correos_duplicates from anon, authenticated;
revoke all on public.neurospark_profile_duplicates from anon, authenticated;
revoke all on public.neurospark_schema_inventory from anon, authenticated;

-- ---------------------------------------------------------------------------
-- 5. Constraints y claves. Se agregan NOT VALID para no destruir ni bloquear
--    datos históricos; se validan automáticamente cuando el contenido cumple.
-- ---------------------------------------------------------------------------

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conrelid = 'public.user_profiles'::regclass
          and contype = 'p'
    ) then
        begin
            alter table public.user_profiles
                add constraint user_profiles_pkey primary key (id);
        exception
            when unique_violation or not_null_violation then
                raise notice 'No se creó PK de user_profiles: revisa IDs en la vista de auditoría.';
        end;
    end if;

    if not exists (
        select 1 from pg_constraint
        where conrelid = 'public.correos'::regclass
          and contype = 'p'
    ) then
        begin
            alter table public.correos
                add constraint correos_pkey primary key (id);
        exception
            when unique_violation or not_null_violation then
                raise notice 'No se creó PK de correos: revisa la columna id.';
        end;
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'ns_profiles_age_range'
          and conrelid = 'public.user_profiles'::regclass
    ) then
        alter table public.user_profiles
            add constraint ns_profiles_age_range
            check (age is null or age between 6 and 17) not valid;
    end if;
    if not exists (
        select 1 from pg_constraint
        where conname = 'ns_profiles_mode_valid'
          and conrelid = 'public.user_profiles'::regclass
    ) then
        alter table public.user_profiles
            add constraint ns_profiles_mode_valid
            check (mode is null or mode in ('child', 'teen')) not valid;
    end if;
    if not exists (
        select 1 from pg_constraint
        where conname = 'ns_profiles_mode_matches_age'
          and conrelid = 'public.user_profiles'::regclass
    ) then
        alter table public.user_profiles
            add constraint ns_profiles_mode_matches_age
            check (
                age is null or mode is null
                or (age between 6 and 11 and mode = 'child')
                or (age between 12 and 17 and mode = 'teen')
            ) not valid;
    end if;
    if not exists (
        select 1 from pg_constraint
        where conname = 'ns_correos_age_range'
          and conrelid = 'public.correos'::regclass
    ) then
        alter table public.correos
            add constraint ns_correos_age_range
            check (age is null or age between 6 and 17) not valid;
    end if;
    if not exists (
        select 1 from pg_constraint
        where conname = 'ns_correos_mode_valid'
          and conrelid = 'public.correos'::regclass
    ) then
        alter table public.correos
            add constraint ns_correos_mode_valid
            check (mode is null or mode in ('child', 'teen')) not valid;
    end if;
    if not exists (
        select 1 from pg_constraint
        where conname = 'ns_correos_mode_matches_age'
          and conrelid = 'public.correos'::regclass
    ) then
        alter table public.correos
            add constraint ns_correos_mode_matches_age
            check (
                age is null or mode is null
                or (age between 6 and 11 and mode = 'child')
                or (age between 12 and 17 and mode = 'teen')
            ) not valid;
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'ns_profiles_user_fk'
          and conrelid = 'public.user_profiles'::regclass
    ) then
        alter table public.user_profiles
            add constraint ns_profiles_user_fk
            foreign key (user_id) references auth.users(id)
            on delete cascade not valid;
    end if;
    if not exists (
        select 1 from pg_constraint
        where conname = 'ns_profiles_parent_fk'
          and conrelid = 'public.user_profiles'::regclass
    ) then
        alter table public.user_profiles
            add constraint ns_profiles_parent_fk
            foreign key (parent_user_id) references auth.users(id)
            on delete restrict not valid;
    end if;
    if not exists (
        select 1 from pg_constraint
        where conname = 'ns_correos_child_fk'
          and conrelid = 'public.correos'::regclass
    ) then
        alter table public.correos
            add constraint ns_correos_child_fk
            foreign key (child_user_id) references auth.users(id)
            on delete cascade not valid;
    end if;
    if not exists (
        select 1 from pg_constraint
        where conname = 'ns_correos_parent_fk'
          and conrelid = 'public.correos'::regclass
    ) then
        alter table public.correos
            add constraint ns_correos_parent_fk
            foreign key (parent_user_id) references auth.users(id)
            on delete restrict not valid;
    end if;
end
$$;

do $$
declare
    constraint_name text;
begin
    foreach constraint_name in array array[
        'ns_profiles_age_range',
        'ns_profiles_mode_valid',
        'ns_profiles_mode_matches_age',
        'ns_correos_age_range',
        'ns_correos_mode_valid',
        'ns_correos_mode_matches_age',
        'ns_profiles_user_fk',
        'ns_profiles_parent_fk',
        'ns_correos_child_fk',
        'ns_correos_parent_fk'
    ]
    loop
        begin
            if constraint_name like 'ns_profiles_%'
               and exists (
                   select 1 from pg_constraint
                   where conname = constraint_name
                     and conrelid = 'public.user_profiles'::regclass
               ) then
                execute format(
                    'alter table public.user_profiles validate constraint %I',
                    constraint_name
                );
            elsif constraint_name like 'ns_correos_%'
                  and exists (
                      select 1 from pg_constraint
                      where conname = constraint_name
                        and conrelid = 'public.correos'::regclass
                  ) then
                execute format(
                    'alter table public.correos validate constraint %I',
                    constraint_name
                );
            end if;
        exception
            when check_violation or foreign_key_violation then
                raise notice 'Constraint % quedó NOT VALID por datos históricos incompatibles.',
                    constraint_name;
        end;
    end loop;
end
$$;

-- Nombres de índices UNIQUE de migraciones anteriores. Solo se retiran si son
-- índices independientes; nunca se toca un índice que respalde un constraint.
do $$
declare
    legacy_index text;
    legacy_oid regclass;
begin
    foreach legacy_index in array array[
        'ns_profiles_user_id_unique',
        'ns_profiles_user_email_unique',
        'ns_profiles_alias_unique',
        'ns_profiles_parent_unique',
        'ns_correos_child_unique',
        'ns_correos_user_email_unique',
        'ns_correos_parent_email_unique'
    ]
    loop
        legacy_oid := to_regclass(format('public.%I', legacy_index));
        if legacy_oid is not null
           and not exists (
               select 1
               from pg_constraint
               where conindid = legacy_oid
           ) then
            execute format('drop index if exists public.%I', legacy_index);
            raise notice 'Índice legado public.% retirado; será reemplazado por la regla segura.',
                legacy_index;
        end if;
    end loop;
end
$$;

-- La unicidad se limita a la fila principal; las filas históricas duplicadas
-- permanecen intactas y consultables.
create unique index if not exists ns_profiles_user_primary_unique
    on public.user_profiles (user_id)
    where user_id is not null and is_primary;

create unique index if not exists ns_correos_child_primary_unique
    on public.correos (child_user_id)
    where child_user_id is not null and is_primary;

create index if not exists ns_profiles_parent_idx
    on public.user_profiles (parent_user_id)
    where parent_user_id is not null;

create index if not exists ns_profiles_email_idx
    on public.user_profiles (lower(user_email))
    where user_email is not null;

create index if not exists ns_profiles_alias_idx
    on public.user_profiles (lower(alias))
    where alias is not null;

create index if not exists ns_correos_parent_idx
    on public.correos (parent_user_id)
    where parent_user_id is not null;

create index if not exists ns_correos_user_email_idx
    on public.correos (lower(user_email))
    where user_email is not null;

create index if not exists ns_correos_parent_email_idx
    on public.correos (lower(parent_email))
    where parent_email is not null;

-- Índices UNIQUE adicionales solo cuando los datos reales lo permiten.
do $$
begin
    if not exists (
        select 1 from public.user_profiles
        where alias is not null and btrim(alias) <> '' and is_primary
        group by lower(alias)
        having count(*) > 1
    ) then
        create unique index if not exists ns_profiles_alias_primary_unique
            on public.user_profiles (lower(alias))
            where alias is not null and is_primary;
    else
        raise notice 'Alias duplicados detectados: se conserva el índice normal y el trigger bloqueará nuevos duplicados.';
    end if;

    if not exists (
        select 1 from public.user_profiles
        where user_email is not null and btrim(user_email) <> '' and is_primary
        group by lower(user_email)
        having count(*) > 1
    ) then
        create unique index if not exists ns_profiles_user_email_primary_unique
            on public.user_profiles (lower(user_email))
            where user_email is not null and is_primary;
    else
        raise notice 'Correos de estudiante duplicados en user_profiles; no se eliminaron.';
    end if;

    if not exists (
        select 1 from public.correos
        where parent_email is not null and btrim(parent_email) <> '' and is_primary
        group by lower(parent_email)
        having count(*) > 1
    ) then
        create unique index if not exists ns_correos_parent_email_primary_unique
            on public.correos (lower(parent_email))
            where parent_email is not null and is_primary;
    else
        raise notice 'Correos parentales duplicados detectados; no se eliminaron.';
    end if;
end
$$;

-- ---------------------------------------------------------------------------
-- 6. Triggers: timestamps, alias único para nuevas escrituras y vínculo
--    familiar inmutable para clientes autenticados.
-- ---------------------------------------------------------------------------

create or replace function public.ns_set_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
    new.updated_at = now();
    return new;
end
$$;

drop trigger if exists ns_profiles_updated_at on public.user_profiles;
create trigger ns_profiles_updated_at
before update on public.user_profiles
for each row execute function public.ns_set_updated_at();

drop trigger if exists ns_correos_updated_at on public.correos;
create trigger ns_correos_updated_at
before update on public.correos
for each row execute function public.ns_set_updated_at();

create or replace function public.ns_enforce_profile_alias()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
    if new.alias is null or btrim(new.alias) = '' or not new.is_primary then
        return new;
    end if;

    if exists (
        select 1
        from public.user_profiles as existing
        where existing.id is distinct from new.id
          and existing.is_primary
          and lower(existing.alias) = lower(new.alias)
    ) then
        raise exception 'El alias "%" ya está en uso.', new.alias
            using errcode = '23505';
    end if;
    return new;
end
$$;

drop trigger if exists ns_profiles_alias_guard on public.user_profiles;
create trigger ns_profiles_alias_guard
before insert or update of alias, is_primary on public.user_profiles
for each row execute function public.ns_enforce_profile_alias();

create or replace function public.ns_enforce_primary_family_link()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
    if not new.is_primary then
        return new;
    end if;

    if new.child_user_id is not null and exists (
        select 1
        from public.correos as existing
        where existing.id is distinct from new.id
          and existing.is_primary
          and existing.child_user_id = new.child_user_id
    ) then
        raise exception 'El hijo ya tiene un vínculo familiar principal.'
            using errcode = '23505';
    end if;

    if new.parent_email is not null
       and btrim(new.parent_email) <> ''
       and exists (
           select 1
           from public.correos as existing
           where existing.id is distinct from new.id
             and existing.is_primary
             and lower(existing.parent_email) = lower(new.parent_email)
       ) then
        raise exception 'El correo del padre/tutor ya tiene un vínculo familiar principal.'
            using errcode = '23505';
    end if;

    return new;
end
$$;

drop trigger if exists ns_correos_family_link_guard on public.correos;
create trigger ns_correos_family_link_guard
before insert or update of child_user_id, parent_email, is_primary on public.correos
for each row execute function public.ns_enforce_primary_family_link();

create or replace function public.ns_protect_family_identity()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
    if coalesce(auth.role(), '') = 'authenticated'
       and (
           old.user_id is distinct from new.user_id
           or old.parent_user_id is distinct from new.parent_user_id
           or old.user_email is distinct from new.user_email
           or old.parent_email is distinct from new.parent_email
           or old.age is distinct from new.age
           or old.mode is distinct from new.mode
           or old.is_primary is distinct from new.is_primary
       ) then
        raise exception 'Los datos familiares sensibles no pueden modificarse desde el cliente.'
            using errcode = '42501';
    end if;
    return new;
end
$$;

drop trigger if exists ns_profiles_family_guard on public.user_profiles;
create trigger ns_profiles_family_guard
before update on public.user_profiles
for each row execute function public.ns_protect_family_identity();

-- ---------------------------------------------------------------------------
-- 7. Funciones públicas mínimas. Se elimina la función anónima que exponía
--    correo parental -> correo del hijo.
-- ---------------------------------------------------------------------------

drop function if exists public.get_student_email_by_parent(text);

create or replace function public.is_alias_available(candidate_alias text)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
    select
        length(btrim(candidate_alias)) between 3 and 24
        and not exists (
            select 1
            from public.user_profiles
            where is_primary
              and lower(alias) = lower(btrim(candidate_alias))
        )
$$;

revoke all on function public.is_alias_available(text) from public;
grant execute on function public.is_alias_available(text) to anon, authenticated;

create or replace function public.get_my_family_context()
returns jsonb
language sql
stable
security invoker
set search_path = public, pg_temp
as $$
    select jsonb_build_object(
        'user_id', profile.user_id,
        'parent_user_id', profile.parent_user_id,
        'user_email', profile.user_email,
        'parent_email', profile.parent_email,
        'alias', profile.alias,
        'full_name', profile.full_name,
        'age', profile.age,
        'mode', profile.mode,
        'state_data', profile.state_data,
        'viewer_role',
            case
                when profile.parent_user_id = auth.uid() then 'parent'
                else 'student'
            end
    )
    from public.user_profiles as profile
    where profile.is_primary
      and (
          profile.user_id = auth.uid()
          or profile.parent_user_id = auth.uid()
      )
    limit 1
$$;

revoke all on function public.get_my_family_context() from public;
grant execute on function public.get_my_family_context() to authenticated;

-- ---------------------------------------------------------------------------
-- 8. RLS idempotente. El padre solo lee; el estudiante actualiza únicamente
--    las columnas otorgadas. service_role permanece exclusivamente servidor.
-- ---------------------------------------------------------------------------

alter table public.user_profiles enable row level security;
alter table public.correos enable row level security;

revoke all on table public.user_profiles from anon, authenticated;
revoke all on table public.correos from anon, authenticated;

grant select on table public.user_profiles to authenticated;
grant update (state_data, alias, full_name, updated_at)
    on table public.user_profiles to authenticated;
grant select on table public.correos to authenticated;
grant select, insert, update, delete
    on table public.user_profiles, public.correos to service_role;

do $$
declare
    sequence_name text;
begin
    foreach sequence_name in array array[
        pg_get_serial_sequence('public.user_profiles', 'id'),
        pg_get_serial_sequence('public.correos', 'id')
    ]
    loop
        if sequence_name is not null then
            execute format('grant usage, select on sequence %s to service_role', sequence_name);
        end if;
    end loop;
end
$$;

do $$
declare
    existing_policy record;
begin
    for existing_policy in
        select schemaname, tablename, policyname
        from pg_policies
        where schemaname = 'public'
          and tablename in ('user_profiles', 'correos')
    loop
        execute format(
            'drop policy if exists %I on %I.%I',
            existing_policy.policyname,
            existing_policy.schemaname,
            existing_policy.tablename
        );
    end loop;
end
$$;

create policy ns_family_profiles_select
on public.user_profiles
for select
to authenticated
using (
    is_primary
    and (
        user_id = (select auth.uid())
        or parent_user_id = (select auth.uid())
        or lower((select auth.jwt() ->> 'email')) = 'sparkneuro64@gmail.com'
    )
);

create policy ns_family_profiles_update_student
on public.user_profiles
for update
to authenticated
using (
    is_primary
    and (
        user_id = (select auth.uid())
        or lower((select auth.jwt() ->> 'email')) = 'sparkneuro64@gmail.com'
    )
)
with check (
    is_primary
    and (
        user_id = (select auth.uid())
        or lower((select auth.jwt() ->> 'email')) = 'sparkneuro64@gmail.com'
    )
);

create policy ns_family_links_select
on public.correos
for select
to authenticated
using (
    is_primary
    and (
        child_user_id = (select auth.uid())
        or parent_user_id = (select auth.uid())
        or lower((select auth.jwt() ->> 'email')) = 'sparkneuro64@gmail.com'
    )
);

-- ---------------------------------------------------------------------------
-- 9. Vistas de diagnóstico. Permiten comprobar duplicados, objetos faltantes
--    y ejecuciones parciales sin modificar ni exponer datos a la aplicación.
-- ---------------------------------------------------------------------------

create or replace view public.neurospark_duplicate_indexes as
with index_catalog as (
    select
        table_class.oid as table_oid,
        table_class.relname as table_name,
        index_meta.indisunique,
        index_meta.indkey::text as indexed_keys,
        index_meta.indclass::text as operator_classes,
        coalesce(pg_get_expr(index_meta.indexprs, index_meta.indrelid), '') as expressions,
        coalesce(pg_get_expr(index_meta.indpred, index_meta.indrelid), '') as predicate,
        index_class.relname as index_name
    from pg_index as index_meta
    join pg_class as table_class on table_class.oid = index_meta.indrelid
    join pg_class as index_class on index_class.oid = index_meta.indexrelid
    join pg_namespace as namespace on namespace.oid = table_class.relnamespace
    where namespace.nspname = 'public'
      and table_class.relname in ('user_profiles', 'correos')
)
select
    table_name,
    indisunique as is_unique,
    indexed_keys,
    expressions,
    predicate,
    count(*)::integer as duplicate_count,
    jsonb_agg(index_name order by index_name) as index_names
from index_catalog
group by table_oid, table_name, indisunique, indexed_keys, operator_classes, expressions, predicate
having count(*) > 1;

create or replace view public.neurospark_duplicate_constraints as
with constraint_catalog as (
    select
        table_class.relname as table_name,
        constraints.contype::text as constraint_type,
        pg_get_constraintdef(constraints.oid, true) as definition,
        constraints.conname as constraint_name
    from pg_constraint as constraints
    join pg_class as table_class on table_class.oid = constraints.conrelid
    join pg_namespace as namespace on namespace.oid = table_class.relnamespace
    where namespace.nspname = 'public'
      and table_class.relname in ('user_profiles', 'correos')
)
select
    table_name,
    constraint_type,
    definition,
    count(*)::integer as duplicate_count,
    jsonb_agg(constraint_name order by constraint_name) as constraint_names
from constraint_catalog
group by table_name, constraint_type, definition
having count(*) > 1;

create or replace view public.neurospark_duplicate_policies as
select
    policies.tablename as table_name,
    policies.cmd,
    policies.roles::text as roles,
    coalesce(policies.qual, '') as using_expression,
    coalesce(policies.with_check, '') as check_expression,
    count(*)::integer as duplicate_count,
    jsonb_agg(policies.policyname order by policies.policyname) as policy_names
from pg_policies as policies
where policies.schemaname = 'public'
  and policies.tablename in ('user_profiles', 'correos')
group by policies.tablename, policies.cmd, policies.roles::text,
         coalesce(policies.qual, ''), coalesce(policies.with_check, '')
having count(*) > 1;

create or replace view public.neurospark_schema_objects as
select
    'function'::text as object_type,
    functions.oid::regprocedure::text as object_name,
    'public'::text as parent_object
from pg_proc as functions
join pg_namespace as namespace on namespace.oid = functions.pronamespace
where namespace.nspname = 'public'
  and functions.proname like 'ns_%'
union all
select
    'trigger',
    triggers.tgname,
    tables.relname
from pg_trigger as triggers
join pg_class as tables on tables.oid = triggers.tgrelid
join pg_namespace as namespace on namespace.oid = tables.relnamespace
where namespace.nspname = 'public'
  and not triggers.tgisinternal
  and tables.relname in ('user_profiles', 'correos')
union all
select
    'view',
    views.viewname,
    views.schemaname
from pg_views as views
where views.schemaname = 'public'
  and views.viewname like 'neurospark_%';

create or replace view public.neurospark_schema_health as
with required_columns(table_name, column_name) as (
    values
        ('user_profiles', 'id'),
        ('user_profiles', 'user_id'),
        ('user_profiles', 'parent_user_id'),
        ('user_profiles', 'user_email'),
        ('user_profiles', 'parent_email'),
        ('user_profiles', 'alias'),
        ('user_profiles', 'full_name'),
        ('user_profiles', 'age'),
        ('user_profiles', 'mode'),
        ('user_profiles', 'state_data'),
        ('user_profiles', 'is_primary'),
        ('correos', 'id'),
        ('correos', 'child_user_id'),
        ('correos', 'parent_user_id'),
        ('correos', 'user_email'),
        ('correos', 'parent_email'),
        ('correos', 'alias'),
        ('correos', 'full_name'),
        ('correos', 'age'),
        ('correos', 'mode'),
        ('correos', 'is_primary')
),
checks as (
    select
        'table'::text as object_type,
        expected.object_name,
        to_regclass(expected.object_name) is not null as is_present
    from (values
        ('public.user_profiles'),
        ('public.correos'),
        ('auth.users')
    ) as expected(object_name)
    union all
    select
        'column',
        format('public.%I.%I', required.table_name, required.column_name),
        exists (
            select 1
            from information_schema.columns
            where table_schema = 'public'
              and table_name = required.table_name
              and column_name = required.column_name
        )
    from required_columns as required
    union all
    select
        'function',
        expected.object_name,
        to_regprocedure(expected.object_name) is not null
    from (values
        ('public.is_alias_available(text)'),
        ('public.get_my_family_context()'),
        ('public.ns_set_updated_at()'),
        ('public.ns_enforce_profile_alias()'),
        ('public.ns_enforce_primary_family_link()'),
        ('public.ns_protect_family_identity()')
    ) as expected(object_name)
    union all
    select
        'index',
        expected.object_name,
        to_regclass(expected.object_name) is not null
    from (values
        ('public.ns_profiles_user_primary_unique'),
        ('public.ns_correos_child_primary_unique')
    ) as expected(object_name)
    union all
    select
        'policy',
        format('public.%I.%I', expected.table_name, expected.policy_name),
        exists (
            select 1
            from pg_policies
            where schemaname = 'public'
              and tablename = expected.table_name
              and policyname = expected.policy_name
        )
    from (values
        ('user_profiles', 'ns_family_profiles_select'),
        ('user_profiles', 'ns_family_profiles_update_student'),
        ('correos', 'ns_family_links_select')
    ) as expected(table_name, policy_name)
)
select object_type, object_name, is_present
from checks;

-- Las vistas de auditoría permanecen reservadas para SQL Editor/service_role.
revoke all on public.neurospark_correos_duplicates from anon, authenticated;
revoke all on public.neurospark_profile_duplicates from anon, authenticated;
revoke all on public.neurospark_schema_inventory from anon, authenticated;
revoke all on public.neurospark_duplicate_indexes from anon, authenticated;
revoke all on public.neurospark_duplicate_constraints from anon, authenticated;
revoke all on public.neurospark_duplicate_policies from anon, authenticated;
revoke all on public.neurospark_schema_objects from anon, authenticated;
revoke all on public.neurospark_schema_health from anon, authenticated;

drop function if exists public._ns_safe_jsonb(text);

-- Fuerza a PostgREST a refrescar tablas y RPC recién creadas.
notify pgrst, 'reload schema';

commit;

-- Resultado visible en SQL Editor. Estas consultas no modifican datos.
select * from public.neurospark_correos_duplicates;
select * from public.neurospark_profile_duplicates;
select * from public.neurospark_duplicate_indexes;
select * from public.neurospark_duplicate_constraints;
select * from public.neurospark_duplicate_policies;
select * from public.neurospark_schema_health
where not is_present;
select * from public.neurospark_schema_objects
order by object_type, parent_object, object_name;
select * from public.neurospark_schema_inventory
where table_name in (
    'correos',
    'user_profiles',
    'neurospark_correos_duplicates',
    'neurospark_profile_duplicates'
)
order by table_name;
